### ISSUE TITLE
Where is redshift process?

### ISSUE THREAD

**Issue by Klomon** [raphaelquintao/QRedshift#41]
When I use QRedshift I dont see process redshift in the system monitor and this script https://gist.github.com/CreamyCookie/d036b66af4e17ea527d08e303eb96145 for mpv don't work. But with applet Redshift (redshift@marvel4u) and redshift-gtk process is and script works well. How QRedshift works w/out running redshift?

**Comment by raphaelquintao** [comment]
**This script will not work with QRedshift** and that's right. 
I don't know how redshift@marvel4u works, but redshift-gtk runs the redshift process in background and keep monitoring his state.
QRedshift runs Redshift in one-shot mode, it means redshift process is called only when changes are made or when triggered by the update interval.
This feature to disable QRedshift for full screen applications has be request before, but for now i have no plans to do that yet, i'm too busy to for now...

**Comment by raphaelquintao** [comment]
I suggest you to use the scroll action to toggle On/Off state, i use that myself.
